export const ErrorCodes = {
  // Auth
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Booking
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',

  // Payment
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',

  // Refund
  REFUND_ALREADY_PROCESSED: 'REFUND_ALREADY_PROCESSED',
  REFUND_NOT_ELIGIBLE: 'REFUND_NOT_ELIGIBLE',

  // Wallet / Lead
  INSUFFICIENT_WALLET: 'INSUFFICIENT_WALLET',
  INSUFFICIENT_LEADS: 'INSUFFICIENT_LEADS',

  // System & Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
} as const;

export type ErrorCodeType = typeof ErrorCodes[keyof typeof ErrorCodes];
