export const LOCATION_CONFIG = {
  LOCATION_ACCURACY_THRESHOLD: Number(process.env.LOCATION_ACCURACY_THRESHOLD || 100),
  LOCATION_MIN_DISTANCE_METERS: Number(process.env.LOCATION_MIN_DISTANCE_METERS || 20),
  LOCATION_OFFLINE_TIMEOUT_SECONDS: Number(process.env.LOCATION_OFFLINE_TIMEOUT_SECONDS || 180),
  LOCATION_REDIS_TTL_SECONDS: Number(process.env.LOCATION_REDIS_TTL_SECONDS || 180),
  LOCATION_REDIS_BUFFER_FLUSH_SECONDS: Number(process.env.LOCATION_REDIS_BUFFER_FLUSH_SECONDS || 15),
  LOCATION_DB_PERSIST_MAX_INTERVAL_MINUTES: Number(process.env.LOCATION_DB_PERSIST_MAX_INTERVAL_MINUTES || 15),
  LOCATION_MAX_SPEED_KMH: Number(process.env.LOCATION_MAX_SPEED_KMH || 150),
};
